// <auto-generated />
using System;
using FranchiseService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FranchiseService.Infrastructure.Migrations
{
    [DbContext(typeof(FranchiseDbContext))]
    partial class AnimeFranchiseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FranchiseService.Domain.Entities.AnimeFranchise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ViewingOrder")
                        .HasColumnType("integer")
                        .HasColumnName("viewing_order");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("anime_franchise", (string)null);
                });

            modelBuilder.Entity("FranchiseService.Domain.Entities.FranchiseTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FranchiseId")
                        .HasColumnType("uuid")
                        .HasColumnName("anime_franchise_id");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.ToTable("anime_franchise_info", (string)null);
                });

            modelBuilder.Entity("FranchiseService.Domain.Entities.FranchiseTranslation", b =>
                {
                    b.HasOne("FranchiseService.Domain.Entities.AnimeFranchise", "AnimeFranchise")
                        .WithMany("FranchiseTranslations")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimeFranchise");
                });

            modelBuilder.Entity("FranchiseService.Domain.Entities.AnimeFranchise", b =>
                {
                    b.Navigation("FranchiseTranslations");
                });
#pragma warning restore 612, 618
        }
    }
}
