services:
  api-gateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
  
  anime-franchises.api:
    image: animefranchises.api
    build:
      context: .
      dockerfile: AnimeFranchises.Api/Dockerfile

  anime-series.api:
    image: animeseries.api
    build:
      context: .
      dockerfile: AnimeSeries.Api/Dockerfile